Repository radicle-dev/radicle-registry, pull requests merged in 2020-03, with the labels that each got.

#247 Adjust project name validations
  cli/src/commands.rs
  client/examples/project_registration.rs
  core/src/lib.rs
  core/src/project_name.rs
  runtime/src/registry.rs
  test-utils/src/lib.rs
Labels: spec, β1

#265 Expose validation errors
  core/src/lib.rs
Labels: β1

#266 Fix failing low transfers
  runtime/src/lib.rs
  runtime/tests/transfer.rs
Labels: bug

#267 Feature/new cli commands
  README.md
  cli/src/commands.rs
  cli/src/main.rs
Labels: cli
